Small typo fix
buildout/wheel pull request #1
Opened 2017-02-14 07:08 UTC by reinout

2017-02-14 07:14 UTC, icemac requested changes
Found another typo.

2017-02-14 07:14 UTC, icemac commented on README.rst
>  Experimental Buildout extension to provude wheel support
Here is another typo: "provude" instead of "provide".

2017-02-14 07:18 UTC, icemac approved these changes

2017-02-22 16:49 UTC, leorochael commented
@jimfulton: OK to squash/merge this PR?

2017-02-22 20:16 UTC, merged